import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    'installation',
    {
      type: 'category',
      label: 'API',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
  ],
  examples: [
    {
      type: 'autogenerated',
      dirName: 'examples',
    }
  ],
};

export default sidebars;
